### ISSUE TITLE
Date race

### ISSUE THREAD

**Issue by djui** [go-fsnotify/fsnotify#99] opened 2015-10-21 15:16 UTC
While race testing some of my code I got the following. Seems like watcher are being close although they have been already removed...

```
WARNING: DATA RACE
Write by goroutine 101:
  runtime.mapdelete()
      /usr/local/Cellar/go/1.5.1/libexec/src/runtime/hashmap.go:511 +0x0
  ./vendor/gopkg.in/fsnotify%2ev1.(*Watcher).Remove()
      ./vendor/gopkg.in/fsnotify.v1/kqueue.go:119 +0x4ed
  ./vendor/gopkg.in/fsnotify%2ev1.(*Watcher).readEvents()
      ./vendor/gopkg.in/fsnotify.v1/kqueue.go:291 +0x878

Previous read by goroutine 189:
  runtime.mapiternext()
      /usr/local/Cellar/go/1.5.1/libexec/src/runtime/hashmap.go:621 +0x0
  ./vendor/gopkg.in/fsnotify%2ev1.(*Watcher).Close()
      ./vendor/gopkg.in/fsnotify.v1/kqueue.go:80 +0x233
  ./vendor/gopkg.in/fsnotify%2ev1.(*Watcher).Close-fm()
      ./foo/foo.go:157 +0x3b
  ..LogCloseError()
      ./log_close_error.go:9 +0x48
  ./foo.(*fooReader).monitor.func1()
      ./foo/foo.go:178 +0x512

Goroutine 101 (running) created at:
  ./vendor/gopkg.in/fsnotify%2ev1.NewWatcher()
      ./vendor/gopkg.in/fsnotify.v1/kqueue.go:61 +0x443
  ./foo.(*fooReader).monitor()
      ./foo/foo.go:146 +0x58
  ./foo.New()
      ./foo/foo.go:48 +0x31b
  ./foo_test.TestClosing()
      ./foo/foo_test.go:118 +0x3e2
  testing.tRunner()
      /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:456 +0xdc

Goroutine 189 (running) created at:
  ./foo.(*fooReader).monitor()
      ./foo/foo.go:181 +0x228
  ./foo.New()
      ./foo/foo.go:48 +0x31b
  ./foo_test.TestClosing()
      ./foo/foo_test.go:118 +0x3e2
  testing.tRunner()
      /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:456 +0xdc
==================
Found 1 data race(s)
```

**Comment by nathany** [comment] 2015-10-21 18:26
yikes. What OS did you encounter this on?

If possible, can you provide a small code sample that reproduces the issue?

**Comment by djui** [comment] 2015-10-21 18:32
OS X 10.11. Will try to shrink down the code into an example. I believe the problem is at https://github.com/go-fsnotify/fsnotify/blob/master/kqueue.go#L75-L80: Locking and assigning `w.watches` to `ws` does not lock `w.watches` while iterating over `ws` in the for loop.

**Comment by nathany** [comment] 2015-10-21 22:32
If it occurs consistently, you could try changing that lock in your local copy of fsnotify to see if it solves the issue.

**Comment by nathany** [comment] 2015-11-17 21:28
Hi Uwe. Any updates on this? I haven't ran into the issue yet myself.

**Comment by omeid** [comment] 2015-11-25 04:17
Shouldn't that unlocked be `defer`ed?

**Comment by nathany** [comment] 2015-11-25 08:46
That might do the trick, but without being able to reproduce the issue, I don't want to just change code and hope it works. Much better if @djui tries it and proves that it fixes his issue.

**Comment by ppknap** [comment] 2015-11-25 23:46
Hi guys!

I created a small test that reproduces this bug.

Generally you:
**READ**(iterate over) `watches` map: https://github.com/go-fsnotify/fsnotify/blob/master/kqueue.go#L80
and
**DELETE** items from it: https://github.com/go-fsnotify/fsnotify/blob/master/kqueue.go#L120

This `Remove` method is triggered by Remove or Rename events here:  https://github.com/go-fsnotify/fsnotify/blob/master/kqueue.go#L307

@omeid you cannot use `defer w.mu.Unlock()` there because `Remove` method also acquires this mutex.

The simplest solution is to create a temporary map and copy all items from `watchers` map to it here: https://github.com/go-fsnotify/fsnotify/blob/master/kqueue.go#L76

then, you will just iterate over this temporary map. `Close()` is meant to be called once, so this extra allocation should be acceptable :)

**Comment by nathany** [comment] 2015-12-10 02:53
@ppknap I like your plan of using a temporary map. Would you be willing to write up a pull request along with a test case?

**Comment by ppknap** [comment] 2015-12-10 11:37
Hi @nathany!

Sure, I could fix this easily but I do not have much time right now.

Tests don't fail because your `.travis.yml` configuration uses default settings for Go builds. Thus, your tests are run with `go test -v ./...` command and don't fire race checker. You may want to add `script: go test -v --race ./...` to your `.travis.yml`.

**Comment by nathany** [comment] 2015-12-11 00:49
Good idea. Thanks.

**Comment by nathany** [comment] 2015-12-17 04:19
@djui The race detector isn't finding any races for me on OS X 10.11.2 with Go 15.2. or tip, but I've added `--race` to Travis CI (which includes OS X).

On the other hand, there are two races happening on Linux. Looking into those in #105. Thanks @ppknap.

**Comment by nathany** [comment] 2015-12-17 04:45
Oh. It showed up now, thanks to @ppknap's TestRemoveWithClose. Not sure why it didn't show up immediately after I merged that in, but oh well. Looking into it.

**Comment by nathany** [comment] 2015-12-17 05:10
Please review #105 and when all is good I'll do a new release.

**Closed** 2015-12-17 18:50 UTC
Labels: BSD (kqueue), bug, OS X (kqueue)
